name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      # The OMDB_KEY environment variable is not strictly needed for tests
      # as api_client.py is mocked to use a fake key or not make calls.
      # However, if any test inadvertently needs it, set a dummy one.
      run: |
        pytest ./tests/
      env:
        OMDB_KEY: dummy_ci_key # For tests, though mocks should prevent actual use